### ISSUE TITLE
client: Method for getting leader and helper aggregator

### ISSUE THREAD

**Issue by inahga** [divviup/divviup-api#1034]
From https://github.com/divviup/divviup-api/pull/1019#discussion_r1591330789. Right now `.aggregators()` of a task returns a `Vec<Aggregator>`, requiring extra code or unwraps to find the leader and helper.

I think we did `Vec<Aggregator>` so as not to overly generalize on a 2-party MPC scheme, but I think by this point we're pretty solidly doing 2-party MPC.

**Comment by branlwyd** [comment]
100%, we could replace the `Vec<Aggregator>` with a pair of fields `leader_aggregator` & `helper_aggregator` -- DAP has now specified to 2 parties & is very unlikely to change from that.

**Comment by tgeoghegan** [comment]
I'm not sure this is correct. There is no suhc method on [`divviup_client::Task`](https://docs.rs/divviup-client/latest/divviup_client/struct.Task.html), and that struct already has the `leader_aggregator_id` and `helper_aggregator_id` fields we'd expect.

 The method in question is [`DivviupClient::aggregators`](https://docs.rs/divviup-client/latest/divviup_client/struct.DivviupClient.html#method.aggregators), which returns a list of the aggregators associated with an account. `Vec<Aggregator>` is correct here, because there could be any number of aggregators available for the account to choose from. But what could be helpful here is a new method `DivviupClient::aggregator(&self, aggregator_id: Uuid) -> ClientResult<Option<Aggregator>>` that would do `GET /aggregators/:aggregator_id` (already supported on the backend) and spare clients the hassle of iterating over the list.

**Comment by inahga** [comment]
> But what could be helpful here is a new method DivviupClient::aggregator(&self, aggregator_id: Uuid) -> ClientResult<Option<Aggregator>> that would do GET /aggregators/:aggregator_id (already supported on the backend) and spare clients the hassle of iterating over the list.

That would work, yes. If I can write:
```rust
let leader_aggregator = client.aggregator(task.leader_aggregator_id).await?;
```
That works for me. (Sorry, one month younger me phrased this as an XY problem).
